version: "3.8"
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis # Assuming your redis server dockerfile is named Dockerfile-redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redisinsight:
    build:
      context: .
      dockerfile: Dockerfile-insight # Assuming your redis insight dockerfile is named Dockerfile-insight
    ports:
      - "5540:5540"
    environment:
      REDISINSIGHT_URL: redis:6379 # Connect to the 'redis' service on port 6379
    networks:
      - redis-network

networks:
  redis-network: