# Use the official Redis image as a base
FROM redis:latest

# (Optional) If you need to customize the Redis configuration,
# you can copy a redis.conf file into the container.
# COPY redis.conf /usr/local/etc/redis/redis.conf

# (Optional) If you want to run Redis with a custom command,
# you can specify it here. For example, to use a custom config:
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

# By default, the Redis image runs redis-server, so you don't need
# to specify a CMD unless you have custom needs.

# Expose the default Redis port
EXPOSE 6379
EXPOSE 5540